import keyMirror from 'keymirror';
// TODO:
// fetchGuestCampaign
// RECEIVE_GUEST_CAMPAIGN_REQUEST: null,
// RECEIVE_GUEST_CAMPAIGN_SUCCESS: null,
// RECEIVE_GUEST_CAMPAIGN_FAILURE: null,

// updateGuestCampaign
// UPDATE_GUEST_CAMPAIGN_REQUEST: null,
// UPDATE_GUEST_CAMPAIGN_SUCCESS: null,
// UPDATE_GUEST_CAMPAIGN_FAILURE: null,

// createGuestCampaign
// CREATE_GUEST_CAMPAIGN_REQUEST: null,
// CREATE_GUEST_CAMPAIGN_SUCCESS: null,
// CREATE_GUEST_CAMPAIGN_FAILURE: null,

// deleteGuestCampaign
// DELETE_GUEST_CAMPAIGN_REQUEST: null,

export default keyMirror({
  RECEIVE_POSTS_REQUEST: null,
  RECEIVE_POSTS_SUCCESS: null,
  RECEIVE_POSTS_FAILURE: null,
  
  SELECT_SUBREDDIT: null
});